resolver: lts-11.2
packages:
  - composite-aeson
  - composite-aeson-refined
  - composite-base
  - composite-ekg
  - composite-opaleye
  - composite-swagger
  - example
flags: {}
extra-package-dbs: []
nix:
  packages:
    - postgresql
    - zlib
