name:                composite-aeson
version:             0.7.6.0
synopsis:            JSON for Vinyl records
description:         Integration between Aeson and Vinyl records allowing records to be easily converted to JSON using automatic derivation, explicit formats, or a mix of both.
homepage:            https://github.com/ConferOpenSource/composite#readme
license:             BSD3
author:              Confer Health, Inc
maintainer:          oss@vitalbio.com
copyright:           2017 Confer Health, Inc., 2020-2021 Vital Biosciences
category:            Records

dependencies:
  - base >= 4.12 && < 5
  - aeson >= 1.1.2.0 && < 1.6
  - aeson-better-errors >= 0.9.1.0 && < 0.10
  - composite-base >= 0.7 && < 0.8
  - containers >= 0.5.7.0 && < 0.7
  - contravariant >= 1.4 && < 1.6
  - generic-deriving >= 1.11.2 && < 1.15
  - hashable >= 1.2.6.1 && < 1.4
  - lens >= 4.15.4 && < 5.1
  - mmorph >= 1.0.9 && < 1.2
  - mtl >= 2.2.1 && < 2.3
  - profunctors >= 5.2.1 && < 5.7
  - scientific >= 0.3.5.1 && < 0.4
  - tagged >= 0.8.5 && < 0.9
  - template-haskell >= 2.11.1.0 && < 2.18
  - text >= 1.2.2.2 && < 1.3
  - time >= 1.6.0.1 && < 1.10
  - unordered-containers >= 0.2.8.0 && < 0.3
  - vector >= 0.12.0.1 && < 0.13
  - vinyl >= 0.5.3 && < 0.14

default-extensions:
  - DataKinds
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - OverloadedStrings
  - PatternSynonyms
  - PolyKinds
  - QuasiQuotes
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns

ghc-options: -Wall -O2

library:
  source-dirs: src

tests:
  composite-aeson-test:
    source-dirs: test
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -fno-warn-orphans
    dependencies:
      - QuickCheck
      - aeson-qq
      - composite-aeson
      - hspec
