name:                composite-ekg
version:             0.6.1.0
synopsis:            EKG Metrics for Vinyl/Frames records
description:         Integration between EKG and Vinyl/Frames records allowing records holding registered metrics to be easily constructed from a type declaration.
homepage:            https://github.com/ConferHealth/composite#readme
license:             BSD3
author:              Confer Health, Inc
maintainer:          oss@confer.health
copyright:           2017 Confer Health, Inc.
category:            Records

dependencies:
  - base >= 4.7 && < 5
  - composite-base >= 0.5.3.0 && < 0.7
  - ekg-core >= 0.1.1.3 && < 0.5
  - lens >= 4.15.4 && < 4.18
  - text >= 1.2.2.2 && < 1.3
  - vinyl >= 0.5.3 && < 0.13

default-extensions:
  - DataKinds
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - OverloadedStrings
  - PolyKinds
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData
  - TemplateHaskell
  - TupleSections
  - TypeFamilies
  - TypeOperators
  - ViewPatterns

ghc-options: -Wall -O2

library:
  source-dirs: src
