name:                composite-swagger
version:             0.7.6.0
synopsis:            Swagger for Vinyl records
description:         Integration between Swagger and Vinyl records allowing easily derivable/explicit Swagger definitions for records.
homepage:            https://github.com/ConferOpenSource/composite#readme
license:             BSD3
author:              Dan Fithian
maintainer:          oss@vitalbio.com
copyright:           2017 Confer Health, Inc., 2020-2021 Vital Biosciences
category:            Records

dependencies:
  - base >= 4.12 && < 5
  - composite-base >= 0.7 && < 0.8
  - insert-ordered-containers >= 0.2.1.0 && < 0.3
  - lens >= 4.15.4 && < 5.1
  - swagger2 >= 2.1.6 && < 2.7
  - template-haskell >= 2.11.1.0 && < 2.17
  - text >= 1.2.2.2 && < 1.3
  - vinyl >= 0.5.3 && < 0.14

default-extensions:
  - DataKinds
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - OverloadedStrings
  - PolyKinds
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData
  - TemplateHaskell
  - TupleSections
  - TypeFamilies
  - TypeOperators
  - ViewPatterns

ghc-options: -Wall -O2

library:
  source-dirs: src

tests:
  composite-swagger-test:
    source-dirs: test
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -fno-warn-orphans
    dependencies:
      - QuickCheck
      - composite-aeson
      - composite-base
      - composite-swagger
      - hspec
