name:                composite-opaleye
version:             0.7.2.0
synopsis:            Opaleye SQL for Vinyl records
description:         Integration between Vinyl records and Opaleye SQL, allowing records to be stored, retrieved, and queried from PostgreSQL.
homepage:            https://github.com/ConferOpenSource/composite#readme
license:             BSD3
author:              Confer Health, Inc.
maintainer:          oss@vitalbio.com
copyright:           2017 Confer Health, Inc., 2020 Vital Biosciences
category:            Records

dependencies:
  - base >= 4.7 && < 5
  - bytestring >= 0.10.8.1 && < 0.11
  - composite-base >= 0.7 && < 0.8
  - lens >= 4.15.4 && < 4.20
  - opaleye >= 0.5.4.0 && < 0.7
  - postgresql-simple >= 0.5.3.0 && < 0.7
  - product-profunctors >= 0.8.0.3 && < 0.12
  - profunctors >= 5.2.1 && < 5.6
  - template-haskell >= 2.11.1.0 && < 2.17
  - text >= 1.2.2.2 && < 1.3
  - vinyl >= 0.5.3 && < 0.14

default-extensions:
  - DataKinds
  - FlexibleContexts
  - FlexibleInstances
  - LambdaCase
  - MultiParamTypeClasses
  - OverloadedStrings
  - PatternSynonyms
  - PolyKinds
  - ScopedTypeVariables
  - StrictData
  - TemplateHaskell
  - TypeFamilies
  - TypeOperators
  - ViewPatterns

ghc-options: -Wall -O2

library:
  source-dirs: src

tests:
  composite-opaleye-test:
    source-dirs: test
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -fno-warn-orphans
    dependencies:
      - QuickCheck
      - composite-opaleye
      - hspec
