name:                composite-base
version:             0.7.2.0
synopsis:            Shared utilities for composite-* packages.
description:         Shared helpers for the various composite packages.
homepage:            https://github.com/ConferOpenSource/composite#readme
license:             BSD3
author:              Confer Health, Inc.
maintainer:          oss@vitalbio.com
copyright:           2017 Confer Health, Inc., 2020 Vital Biosciences
category:            Records

dependencies:
  - base >= 4.7 && < 5
  - deepseq >= 1.4 && < 1.5
  - exceptions >= 0.8.3 && < 0.11
  - lens >= 4.15.4 && < 4.20
  - monad-control >= 1.0.2.2 && < 1.1
  - mtl >= 2.2.1 && < 2.3
  - profunctors >= 5.2.1 && < 5.6
  - template-haskell >= 2.11.1.0 && < 2.17
  - text >= 1.2.2.2 && < 1.3
  - transformers >= 0.5.2.0 && < 0.6
  - transformers-base >= 0.4.4 && < 0.5
  - unliftio-core >= 0.1.0.0 && < 0.3.0.0
  - vinyl >= 0.5.3 && < 0.14

default-extensions:
  - ConstraintKinds
  - DataKinds
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns

ghc-options: -Wall -O2

library:
  source-dirs: src

tests:
  composite-base-test:
    source-dirs: test
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -fno-warn-orphans
    dependencies:
      - QuickCheck
      - composite-base
      - hspec
